services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-recommendation
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html

